### PR TITLE
Thats how it works

### PR DESCRIPTION
**Pull request by fennectech**

### CODE REVIEW

**Comment by magi009** [comment]
Hello, can i upload to my discord channel?

**Comment by hax4dazy** [comment]
What

**Comment by CrafterPika** [comment]
*shrek*

**Comment by magi009** [comment]
Deepsea, can i upload?

**Comment by hax4dazy** [comment]
Euh. That doesn't help... I'm going to assume you mean upload the full zip file to your discord server. If that's the case then yes. Otherwise I've got no idea what you mean

**Comment by Slluxx** [comment]
@magi009 id say he shopuld only link to github. he can do whatever he wants but downloads should be made from official sources. thats where the newest versions are and you can be sure they are not altered with.

if he wants to upload it though, there is nothing that can stop him.

Anyway, this is not for discussions - so ill lock the coversation now

**Pull request closed without merging**
