### PR TITLE
add some modules

### PR DESCRIPTION
**Pull request by ca1e**
add some "useful" modules[have been tested]

### CODE REVIEW

**Comment by hax4dazy** [comment]
Why would we use awoo when we're using tinwoo

**Comment by ca1e** [comment]
> Why would we use awoo when we're using tinwoo

I just add the module for awoo, you can use whatever you like, just need edit the module list of setting

**Comment by hax4dazy** [comment]
I don't think that we would use any of these imo. I personally haven't heard of some of them and most of them are just gonna DeepSea more bloated. We also a while back removed lockpick because it wasn't used.

**Comment by ca1e** [comment]
its okay, just saw some comments https://github.com/ca1e/DeepSea/commit/d1a596f18f6b83f86ce488ac50f6d5561acc4918#commitcomment-56547859 maybe its useful for someone I think.
And I thought it maybe useful for us to maintain a module hub like this

**Comment by Slluxx** [comment]
- patches wont be included because nintendo and github have a habbit of deleting repositorys with them. you can download them easily from AIO updater or you can create a custom build on our website with them included.
- nxdumptool is something we have to discuss as what its does is piracy.
- linkalho is probably for people who used incognito? i have never needed it at all and i know no one who did (and their reasons).
- dbi ; what features are wanted from this? as you also include awoo, even though tinwoo is already in the package and has more features than awoo.
- breeze ; an edizon alternative that originates from EdizonSE? That seems interesting indeed.
- zing ; if we include breeze, will obviously also include zing.
- sysdvr ; why is this included? this is such a niche thing that it seems its in just because you want to use it. You can get it from the appstore if you want to and **if** we wanted to include it it would probably in a different package.
- quickntp ; yeah this is kinda usefull. we will probably include this once we include a 90dns mitm file.
- lockpick got removed because no one really used it but if its needed, we can include it again.
- capture sight again seems like such a niche thing. maybe 5% of all people using the cfw actually play pokemon so this would just be junk for people who dont.
- awoo wont be included because we have tinwoo, which has more features and is not offensive torwards "minorities".
- amiigo; why does this tool offer that the emuiibo tesla overlay does not offer? Its more clean and you dont have to leave your game to use it.

**Comment by Slluxx** [comment]
BTW the question on your forked deepsea repo was because it seems like your are missing things on deepsea that we *could* add. Creating and updating a repository and creating releases is a lot of work. More work than just downloading them through the appstore. DeepSea is meant to be a basic "starter" with hopefully no unused modules by the majority. Adding things that are targeted to a specific group of people is not really "good" in that sense.
 
 We love when people help us, suggest things and make deepsea better, which is just not possile if everyon forks it and makes personal changes for themself. Thats why i commented on the fork

**Comment by ca1e** [comment]
> BTW the question on your forked deepsea repo was because it seems like your are missing things on deepsea that we _could_ add. Creating and updating a repository and creating releases is a lot of work. More work than just downloading them through the appstore. DeepSea is meant to be a basic "starter" with hopefully no unused modules by the majority. Adding things that are targeted to a specific group of people is not really "good" in that sense.
> 
> We love when people help us, suggest things and make deepsea better, which is just not possile if everyon forks it and makes personal changes for themself. Thats why i commented on the fork

I agree.this is not for some special change. I dont think we need all these modules once all yet.literally I jsut keep these module settings for a collection.or maybe we can maintain a repo like a module hub?

**Comment by Slluxx** [comment]
> > BTW the question on your forked deepsea repo was because it seems like your are missing things on deepsea that we _could_ add. Creating and updating a repository and creating releases is a lot of work. More work than just downloading them through the appstore. DeepSea is meant to be a basic "starter" with hopefully no unused modules by the majority. Adding things that are targeted to a specific group of people is not really "good" in that sense.
> > We love when people help us, suggest things and make deepsea better, which is just not possile if everyon forks it and makes personal changes for themself. Thats why i commented on the fork
> 
> I agree.this is not for some special change. that is why I dont pr the `custom` branch from my fork. I dont think we need all these modules once all yet.literally I jsut keep these module settings for a collection.or maybe we can maintain a repo like a module hub?

have you seen [https://builder.teamneptune.net/](https://builder.teamneptune.net/) ?
We are working on a new version of that, which will have a "module hub". anyone will be able to edit and add modules to that system and you can create a custom release and share its url. This is completely decoupled from this repo though and anything in here will not affect the new builder. Infact, the builder will replace anything made here.

**Comment by ca1e** [comment]
oh I hadnt seen the builder website yet.Its great and I will happy to contribute.
I'll close this PR and waiting to contribute the new version builder :rocket:

**Pull request closed without merging**
