### PR TITLE
Refactor module definitions

### PR DESCRIPTION
**Pull request by marco-calautti**
There were a lot repeated json entries for the same modules, in the different jsons. This pull request factors out modules definitions from packages definitions. The sdsetup package definition has also been refactored, but it seems it has never been used as it has some bugs even in the previous version of the builder.

### CODE REVIEW

**Comment by Slluxx** [comment]
Nice. i wanted to refactor the build as a whole already and thats a pretty good start!

**Comment by marco-calautti** [comment]
Thanks. I have been thinking that modules could take optional parameters that one can specify in the packages definitions. So the same module can be downloaded in a slightly different way, e.g. atmosphere could be downloaded in "vanilla" form, without removing the reboot_payload.bin, etc.

**Comment by marco-calautti** [comment]
I refactored a bit more. The command-based approach for building was becoming a bit heavy, as everytime a package is introduced, a new command needed to be introduced, and different parts of the code changed. Now each package comes with its own name, and a parameter specifying whether it is an sdsetup package or not. So now, it is enough to give the builder the json file of the package to build, and the output zip.
Moreover, packages, when specifying the modules they include, can also pass optional parameters to the modules, to further customize the module download/preparation phase.

**Comment by Slluxx** [comment]
Give me one or two days to completly review your changes. I'll either merge them or add a comment when done :)

btw are you in our discord server?

**Comment by marco-calautti** [comment]
Sure. Yes, I am, my nickname there is Calivi.

**Pull request merged**
